from datetime import date, datetime
from pathlib import Path
from sqlmodel import Field, SQLModel, create_engine

# Data models: each class is both a Pydantic model and a database table schema.
class Food(SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)
    name_zh: str
    name_en: str
    kcal_per_100g: float
    protein_per_100g: float
    carbs_per_100g: float
    fat_per_100g: float


class DietNote(SQLModel, table=True):
    """Daily diet note holding both targets and actual intake, used for
    summaries and analysis."""
    id: int | None = Field(default=None, primary_key=True)
    log_date: date = Field(default_factory=date.today)

    # User-defined targets (submitted by the frontend or generated by the system)
    target_calories: float | None = None
    target_protein_g: float | None = None
    target_carbs_g: float | None = None
    target_fat_g: float | None = None

    # Actual intake for the day (used for summaries)
    actual_calories: float | None = None
    actual_protein_g: float | None = None
    actual_carbs_g: float | None = None
    actual_fat_g: float | None = None

    advice: str | None = None


class Meal(SQLModel, table=True):
    """A confirmed-intake record — the core of the meal history. Every meal
    can be looked up by user and by date."""
    id: int | None = Field(default=None, primary_key=True)
    user_id: int | None = Field(default=None, index=True)
    log_date: date = Field(default_factory=date.today)
    created_at: datetime = Field(default_factory=datetime.now)

    total_kcal: float = 0.0
    total_protein_g: float = 0.0
    total_carbs_g: float = 0.0
    total_fat_g: float = 0.0

    # Per-food breakdown of the meal (JSON string:
    # [{food_id, name_zh, weight_g, kcal, ...}])
    items_json: str | None = None
    advice: str | None = None


class UserProfile(SQLModel, table=True):
    """User body metrics plus the targets computed from them."""
    id: int | None = Field(default=None, primary_key=True)
    name: str | None = None  # display name; if blank, the frontend generates a random one
    age: int
    gender: str  # 'male' or 'female'
    height_cm: float
    weight_kg: float
    activity_level: float  # activity factor, e.g. 1.2, 1.375, 1.55
    diet_mode: str  # 'fat_loss' | 'balance' | 'muscle_gain'

    # Targets computed by the system
    target_calories: float | None = None
    target_protein_g: float | None = None
    target_fat_g: float | None = None
    target_carbs_g: float | None = None

# The database file lives next to this module (absolute path) so that every
# launch mode — dev server or packaged app — points at the same database
# regardless of the working directory.
DB_PATH = Path(__file__).resolve().parent / "database.db"
sqlite_file_name = str(DB_PATH)
sqlite_url = f"sqlite:///{sqlite_file_name}"

engine = create_engine(sqlite_url, echo=False)


def create_db_and_tables():
    SQLModel.metadata.create_all(engine)


if __name__ == "__main__":
    create_db_and_tables()
    print("Database and Food table initialized successfully!")